#!/usr/bin/env bash
# setup-covibe.sh — Hybrid LLM Dev System Setup
# Installs: Ollama, qwen2.5-coder:7b, co-vibe, covibe-router
# Usage: bash setup-covibe.sh
set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════╗"
echo "║   Lore-Anchor Hybrid LLM Dev System Setup   ║"
echo "║   Local Ollama + Claude co-vibe Router      ║"
echo "╚══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Ollama ──────────────────────────────────────────────────────────────────
info "Checking Ollama..."
if ! command -v ollama &>/dev/null; then
  info "Installing Ollama..."
  if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install ollama 2>/dev/null || curl -fsSL https://ollama.ai/install.sh | sh
  else
    curl -fsSL https://ollama.ai/install.sh | sh
  fi
  ok "Ollama installed"
else
  ok "Ollama already installed: $(ollama --version)"
fi

# Start Ollama in background if not running
if ! curl -sf http://localhost:11434/api/tags &>/dev/null; then
  info "Starting Ollama server..."
  ollama serve &>/tmp/ollama.log &
  sleep 3
fi

# ── 2. Pull coding model ──────────────────────────────────────────────────────
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5-coder:7b}"
info "Pulling ${OLLAMA_MODEL} (this may take a few minutes)..."
if ollama list | grep -q "${OLLAMA_MODEL%%:*}"; then
  ok "${OLLAMA_MODEL} already available"
else
  ollama pull "$OLLAMA_MODEL"
  ok "Pulled ${OLLAMA_MODEL}"
fi

# Optional: smaller fallback model for very simple tasks
FAST_MODEL="qwen2.5-coder:1.5b"
info "Pulling ${FAST_MODEL} (fast/tiny for trivial tasks)..."
if ! ollama list | grep -q "qwen2.5-coder:1.5b"; then
  ollama pull "$FAST_MODEL" &
fi

# ── 3. co-vibe ────────────────────────────────────────────────────────────────
COVIBE_DIR="$HOME/co-vibe"
info "Setting up co-vibe..."
if [[ ! -d "$COVIBE_DIR" ]]; then
  git clone https://github.com/ochyai/co-vibe "$COVIBE_DIR"
  ok "co-vibe cloned to $COVIBE_DIR"
else
  ok "co-vibe already cloned"
  git -C "$COVIBE_DIR" pull --ff-only 2>/dev/null || true
fi

# ── 4. co-vibe .env config ────────────────────────────────────────────────────
COVIBE_ENV="$COVIBE_DIR/.env"
info "Writing co-vibe config..."

# Detect existing keys from current project .env files
ANTHROPIC_KEY=""
OPENAI_KEY=""
GROQ_KEY=""

for env_file in .env .env.local ../.env; do
  if [[ -f "$env_file" ]]; then
    ANTHROPIC_KEY="${ANTHROPIC_KEY:-$(grep -E '^ANTHROPIC_API_KEY=' "$env_file" | cut -d= -f2- | tr -d '"' | tr -d "'" 2>/dev/null || true)}"
    OPENAI_KEY="${OPENAI_KEY:-$(grep -E '^OPENAI_API_KEY=' "$env_file" | cut -d= -f2- | tr -d '"' | tr -d "'" 2>/dev/null || true)}"
    GROQ_KEY="${GROQ_KEY:-$(grep -E '^GROQ_API_KEY=' "$env_file" | cut -d= -f2- | tr -d '"' | tr -d "'" 2>/dev/null || true)}"
  fi
done

cat > "$COVIBE_ENV" << EOF
# co-vibe Hybrid Config — auto-generated by setup-covibe.sh
# Strategy: Ollama first (local/free), escalate to Claude for complex tasks

# ── Anthropic (Claude) — complex tasks only ──
ANTHROPIC_API_KEY=${ANTHROPIC_KEY:-your_anthropic_key_here}

# ── OpenAI — medium fallback ──
OPENAI_API_KEY=${OPENAI_KEY:-your_openai_key_here}

# ── Groq — fast medium tasks (free tier generous) ──
GROQ_API_KEY=${GROQ_KEY:-your_groq_key_here}

# ── Ollama — local, primary for simple/medium tasks ──
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=qwen2.5-coder:7b

# ── Default strategy: routes by complexity ──
# auto   → AI decides (recommended)
# fast   → Groq/Ollama first
# cheap  → Haiku/Ollama first
# strong → Sonnet/Opus for hard problems
COVIBE_DEFAULT_STRATEGY=auto
COVIBE_OLLAMA_PRIORITY=true

# ── Cost guardrails ──
COVIBE_MAX_COST_PER_SESSION_USD=2.0
EOF

ok "co-vibe config written to $COVIBE_ENV"

# ── 5. Router API dependencies ────────────────────────────────────────────────
ROUTER_DIR="$(cd "$(dirname "$0")/covibe-router" && pwd)"
info "Installing router dependencies..."
if [[ -d "$ROUTER_DIR" ]]; then
  pip3 install -r "$ROUTER_DIR/requirements.txt" -q
  ok "Router dependencies installed"
else
  warn "covibe-router directory not found, skipping"
fi

# ── 6. ngrok (optional — exposes router for Make.com webhooks) ────────────────
info "Checking ngrok for Make.com webhook tunnel..."
if ! command -v ngrok &>/dev/null; then
  warn "ngrok not installed. To expose local router to Make.com:"
  warn "  brew install ngrok  (macOS)"
  warn "  then: ngrok http 8888"
  warn "  or: deploy router to Railway (see covibe-router/railway.toml)"
else
  ok "ngrok available"
fi

# ── 7. Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete! System ready.${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo "  Start local router:    python3 covibe-router/router.py"
echo "  Chat with co-vibe:     python3 ~/co-vibe/co-vibe.py"
echo "  Simple task (local):   python3 ~/co-vibe/co-vibe.py --strategy fast"
echo "  Complex task (Claude): python3 ~/co-vibe/co-vibe.py --strategy strong"
echo "  Metrics dashboard:     curl http://localhost:8888/metrics | jq"
echo ""
echo "  For Make.com integration, expose the router:"
echo "    ngrok http 8888"
echo "    → paste ngrok URL into Make scenario HTTP module"
echo ""
