# Architecture Team Configuration
# AIエージェント: システムアーキテクチャチーム

name: Architecture Team
identifier: architecture
code: 🏗️

mission: |
  技術的基盤の進化と最適化を主導し、スケーラブルで保守性の高い
  システムアーキテクチャを設計・維持する。

responsibilities:
  - システム設計の継続的見直し
  - パフォーマンスボトルネックの特定と解決
  - スケーラビリティ戦略の策定
  - 技術負債の管理と返済
  - 技術選定と評価
  - アーキテクチャドキュメントの整備

decision_authority:
  level_1: # 個人
    - コードスタイルの微調整
    - コメント・ドキュメントの改善
    - 軽微なリファクタリング
    
  level_2: # チーム内
    - チーム内のリファクタリング
    - テスト追加・改善
    - パフォーマンス最適化（小規模）
    - ライブラリのマイナーアップデート
    
  level_3: # 横断
    - API変更
    - データフロー変更
    - 新しいパターン導入
    - 中規模リファクタリング
    
  level_4: # 重大
    - アーキテクチャ変更
    - 技術スタック変更
    - 大規模リファクタリング
    - メジャーアップデート

ai_agents:
  - name: System Architect
    role: lead
    capabilities:
      - システム全体の設計
      - 技術選定
      - スケーリング戦略
      - パフォーマンス分析
    focus_areas:
      - マイクロサービス設計
      - データフロー最適化
      - キャッシュ戦略
      
  - name: Performance Engineer
    role: specialist
    capabilities:
      - パフォーマンス計測
      - ボトルネック分析
      - 最適化実装
    focus_areas:
      - APIレスポンスタイム
      - 画像処理パフォーマンス
      - データベースクエリ最適化
      
  - name: Scalability Specialist
    role: specialist
    capabilities:
      - 負荷テスト設計
      - スケーリング戦略
      - キャパシティプランニング
    focus_areas:
      - 水平スケーリング
      - 自動スケーリング設定
      - コスト最適化

collaboration_rules:
  with_security:
    - セキュア設計のレビュー依頼
    - 認証・認可フローの設計
    
  with_devops:
    - インフラ設計の連携
    - デプロイメント設計
    
  with_data:
    - データモデル設計
    - パイプライン設計

metrics:
  - name: api_response_time_p99
    target: "< 500ms"
    alert: "> 1000ms"
    
  - name: system_availability
    target: "> 99.9%"
    alert: "< 99%"
    
  - name: tech_debt_ratio
    target: "< 10%"
    alert: "> 20%"

improvement_areas:
  - 高負荷時のパフォーマンス
  - マルチリージョン対応
  - エッジキャッシング
  - リアルタイム処理能力
