# Data Team Configuration
# AIã‚¨ãƒ¼ã‚¸ã‚§ãƒ³ãƒˆ: ãƒ‡ãƒ¼ã‚¿ãƒãƒ¼ãƒ 

name: Data Team
identifier: data
code: ðŸ“Š

mission: |
  ãƒ‡ãƒ¼ã‚¿é§†å‹•åž‹æ„æ€æ±ºå®šã‚’å®Ÿç¾ã—ã€ä¾¡å€¤ã‚ã‚‹æ´žå¯Ÿã‚’
  å…¨ãƒãƒ¼ãƒ ã«æä¾›ã™ã‚‹ã€‚

responsibilities:
  - ãƒ‡ãƒ¼ã‚¿ãƒ‘ã‚¤ãƒ—ãƒ©ã‚¤ãƒ³ã®ç®¡ç†
  - MLãƒ¢ãƒ‡ãƒ«ã®ç¶™ç¶šçš„å­¦ç¿’
  - ã‚¢ãƒŠãƒªãƒ†ã‚£ã‚¯ã‚¹ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰
  - ç•°å¸¸æ¤œçŸ¥ã‚·ã‚¹ãƒ†ãƒ 
  - ãƒ‡ãƒ¼ã‚¿å“è³ªç®¡ç†
  - äºˆæ¸¬ãƒ¢ãƒ‡ãƒ«æ§‹ç¯‰

decision_authority:
  level_2: # ãƒãƒ¼ãƒ å†…
    - ãƒ‡ãƒ¼ã‚¿ã‚¹ã‚­ãƒ¼ãƒžå¤‰æ›´ï¼ˆéžç ´å£Šï¼‰
    - ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰æ›´æ–°
    - MLãƒ¢ãƒ‡ãƒ«ãƒžã‚¤ãƒŠãƒ¼ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆ
    
  level_3: # æ¨ªæ–­
    - ãƒ‡ãƒ¼ã‚¿ã‚¹ã‚­ãƒ¼ãƒžå¤‰æ›´ï¼ˆç ´å£Šçš„ï¼‰
    - MLãƒ¢ãƒ‡ãƒ«ãƒ¡ã‚¸ãƒ£ãƒ¼ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆ
    - æ–°ã—ã„ãƒ‡ãƒ¼ã‚¿ã‚½ãƒ¼ã‚¹è¿½åŠ 
    - ã‚¢ãƒ©ãƒ¼ãƒˆé–¾å€¤èª¿æ•´
    
  level_4: # é‡å¤§
    - ãƒ‡ãƒ¼ã‚¿ã‚¢ãƒ¼ã‚­ãƒ†ã‚¯ãƒãƒ£å¤‰æ›´
    - æ–°ã—ã„MLã‚·ã‚¹ãƒ†ãƒ å°Žå…¥

ai_agents:
  - name: Data Engineer
    role: lead
    capabilities:
      - ãƒ‡ãƒ¼ã‚¿ãƒ‘ã‚¤ãƒ—ãƒ©ã‚¤ãƒ³æ§‹ç¯‰
      - ETL/ELTè¨­è¨ˆ
      - ãƒ‡ãƒ¼ã‚¿å“è³ªç®¡ç†
    focus_areas:
      - ãƒªã‚¢ãƒ«ã‚¿ã‚¤ãƒ å‡¦ç†
      - ãƒ‡ãƒ¼ã‚¿ãƒ¬ã‚¤ã‚¯
      - ãƒ‡ãƒ¼ã‚¿ã‚¦ã‚§ã‚¢ãƒã‚¦ã‚¹
      
  - name: ML Engineer
    role: specialist
    capabilities:
      - MLãƒ¢ãƒ‡ãƒ«é–‹ç™º
      - ãƒ¢ãƒ‡ãƒ«é‹ç”¨
      - MLOps
    focus_areas:
      - ç•°å¸¸æ¤œçŸ¥
      - äºˆæ¸¬ãƒ¢ãƒ‡ãƒ«
      - æŽ¨è–¦ã‚·ã‚¹ãƒ†ãƒ 
      
  - name: Analytics Specialist
    role: specialist
    capabilities:
      - ãƒ‡ãƒ¼ã‚¿åˆ†æž
      - ãƒ¬ãƒãƒ¼ãƒˆä½œæˆ
      - å¯è¦–åŒ–
    focus_areas:
      - KPIè¿½è·¡
      - ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚»ã‚°ãƒ¡ãƒ³ãƒˆ
      - ãƒˆãƒ¬ãƒ³ãƒ‰åˆ†æž

collaboration_rules:
  with_all:
    - ãƒ‡ãƒ¼ã‚¿æä¾›
    - åˆ†æžæ”¯æ´
    - ã‚¤ãƒ³ã‚µã‚¤ãƒˆå…±æœ‰
    
  with_architecture:
    - ãƒ‡ãƒ¼ã‚¿ãƒ•ãƒ­ãƒ¼è¨­è¨ˆ
    
  with_product:
    - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ‡ãƒ¼ã‚¿åˆ†æž

metrics:
  - name: data_pipeline_uptime
    target: "> 99.5%"
    alert: "< 98%"
    
  - name: ml_model_accuracy
    target: "> 90%"
    alert: "< 80%"
    
  - name: data_freshness
    target: "< 15min"
    alert: "> 1h"
    
  - name: data_quality_score
    target: "> 95%"
    alert: "< 90%"

improvement_areas:
  - ãƒªã‚¢ãƒ«ã‚¿ã‚¤ãƒ åˆ†æž
  - è‡ªå‹•ç•°å¸¸æ¤œçŸ¥
  - MLè‡ªå‹•å†å­¦ç¿’
  - ã‚»ãƒ«ãƒ•ã‚µãƒ¼ãƒ“ã‚¹åˆ†æž
