# Product Team Configuration
# AIã‚¨ãƒ¼ã‚¸ã‚§ãƒ³ãƒˆ: ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆãƒãƒ¼ãƒ 

name: Product Team
identifier: product
code: ðŸŽ¨

mission: |
  ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®å‰µä½œæ´»å‹•ã‚’å®ˆã‚‹æœ€é«˜ã®ä½“é¨“ã‚’è¨­è¨ˆã—ã€
  ç¶™ç¶šçš„ãªä¾¡å€¤æä¾›ã‚’å®Ÿç¾ã™ã‚‹ã€‚

responsibilities:
  - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ•ã‚£ãƒ¼ãƒ‰ãƒãƒƒã‚¯åˆ†æž
  - UXæ”¹å–„ææ¡ˆã®è‡ªå‹•ç”Ÿæˆ
  - æ©Ÿèƒ½å„ªå…ˆåº¦ã®å‹•çš„èª¿æ•´
  - å“è³ªãƒ¡ãƒˆãƒªã‚¯ã‚¹ã®ç›£è¦–
  - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒªã‚µãƒ¼ãƒ
  - ãƒ­ãƒ¼ãƒ‰ãƒžãƒƒãƒ—ç®¡ç†

decision_authority:
  level_1: # å€‹äºº
    - UIãƒ†ã‚­ã‚¹ãƒˆå¤‰æ›´
    - ã‚¹ã‚¿ã‚¤ãƒ«èª¿æ•´
    - ãƒžã‚¤ã‚¯ãƒ­ã‚³ãƒ”ãƒ¼æ”¹å–„
    
  level_2: # ãƒãƒ¼ãƒ å†…
    - UI/UXå¾®èª¿æ•´
    - ãƒã‚°ä¿®æ­£å„ªå…ˆåº¦
    - å°è¦æ¨¡æ©Ÿèƒ½è¿½åŠ 
    
  level_3: # æ¨ªæ–­
    - ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼å¤‰æ›´
    - æ–°æ©Ÿèƒ½å°Žå…¥ï¼ˆå°ã€œä¸­è¦æ¨¡ï¼‰
    - ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚¨ã‚¯ã‚¹ãƒšãƒªã‚¨ãƒ³ã‚¹å¤§å¹…å¤‰æ›´
    
  level_4: # é‡å¤§
    - è£½å“ãƒ“ã‚¸ãƒ§ãƒ³å¤‰æ›´
    - å¤§è¦æ¨¡æ©Ÿèƒ½è¿½åŠ 
    - ã‚¿ãƒ¼ã‚²ãƒƒãƒˆãƒ¦ãƒ¼ã‚¶ãƒ¼å¤‰æ›´

ai_agents:
  - name: UX Researcher
    role: lead
    capabilities:
      - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒªã‚µãƒ¼ãƒ
      - è¡Œå‹•åˆ†æž
      - ãƒšãƒ«ã‚½ãƒŠæ›´æ–°
    focus_areas:
      - ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚¸ãƒ£ãƒ¼ãƒ‹ãƒ¼
      - ãƒšã‚¤ãƒ³ãƒã‚¤ãƒ³ãƒˆç‰¹å®š
      - æ©Ÿä¼šç™ºè¦‹
      
  - name: Feature Designer
    role: specialist
    capabilities:
      - æ©Ÿèƒ½è¨­è¨ˆ
      - ä»•æ§˜ä½œæˆ
      - ãƒ—ãƒ­ãƒˆã‚¿ã‚¤ãƒ”ãƒ³ã‚°
    focus_areas:
      - æ©Ÿèƒ½è¦ä»¶å®šç¾©
      - ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚¹ãƒˆãƒ¼ãƒªãƒ¼
      - å—ã‘å…¥ã‚ŒåŸºæº–
      
  - name: Quality Assurance
    role: specialist
    capabilities:
      - ãƒ†ã‚¹ãƒˆè¨­è¨ˆ
      - å“è³ªç›£è¦–
      - ãƒã‚°åˆ†æž
    focus_areas:
      - ãƒ†ã‚¹ãƒˆã‚«ãƒãƒ¬ãƒƒã‚¸
      - å“è³ªãƒ¡ãƒˆãƒªã‚¯ã‚¹
      - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ¬ãƒãƒ¼ãƒˆåˆ†æž

collaboration_rules:
  with_growth:
    - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ‹ãƒ¼ã‚ºä¼é”
    - æˆé•·æ©Ÿä¼šã®ç‰¹å®š
    
  with_architecture:
    - æŠ€è¡“çš„å®Ÿç¾æ€§ç¢ºèª
    - ãƒ‘ãƒ•ã‚©ãƒ¼ãƒžãƒ³ã‚¹è¦ä»¶
    
  with_data:
    - ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ‡ãƒ¼ã‚¿åˆ†æž
    - A/Bãƒ†ã‚¹ãƒˆåˆ†æž

metrics:
  - name: nps_score
    target: "> 50"
    alert: "< 30"
    
  - name: feature_adoption_rate
    target: "> 40%"
    alert: "< 20%"
    
  - name: time_to_value
    target: "< 5min"
    alert: "> 10min"
    
  - name: support_ticket_satisfaction
    target: "> 4.0"
    alert: "< 3.5"

improvement_areas:
  - ã‚ªãƒ³ãƒœãƒ¼ãƒ‡ã‚£ãƒ³ã‚°æœ€é©åŒ–
  - ãƒ‘ãƒ¼ã‚½ãƒŠãƒ©ã‚¤ã‚ºãƒ‰ä½“é¨“
  - ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£
  - ãƒ¢ãƒã‚¤ãƒ«ã‚¨ã‚¯ã‚¹ãƒšãƒªã‚¨ãƒ³ã‚¹
