# Research Team Configuration
# AIã‚¨ãƒ¼ã‚¸ã‚§ãƒ³ãƒˆ: ç ”ç©¶ãƒãƒ¼ãƒ 

name: Research Team
identifier: research
code: ðŸ”¬

mission: |
  æŠ€è¡“çš„å„ªä½æ€§ã‚’ç¶­æŒã—ã€æ–°ã—ã„è„…å¨ã¨æŠ€è¡“ã‚’
  å…ˆå–ã‚Šã—ã¦ç ”ç©¶ã™ã‚‹ã€‚

responsibilities:
  - æœ€æ–°AIæŠ€è¡“ã®èª¿æŸ»
  - æ•µå¯¾çš„æ©Ÿæ¢°å­¦ç¿’ã®ç ”ç©¶
  - ç‰¹è¨±ãƒ»è«–æ–‡ã®ç›£è¦–
  - ãƒ—ãƒ­ãƒˆã‚¿ã‚¤ãƒ”ãƒ³ã‚°
  - æŠ€è¡“ãƒˆãƒ¬ãƒ³ãƒ‰åˆ†æž
  - ã‚¤ãƒŽãƒ™ãƒ¼ã‚·ãƒ§ãƒ³ææ¡ˆ

decision_authority:
  level_2: # ãƒãƒ¼ãƒ å†…
    - ç ”ç©¶ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆé¸å®š
    - PoCå®Ÿæ–½
    
  level_3: # æ¨ªæ–­
    - æ–°æŠ€è¡“å®Ÿé¨“
    - å¤–éƒ¨ç ”ç©¶æ©Ÿé–¢ã¨ã®é€£æº
    
  level_4: # é‡å¤§
    - æ–°æŠ€è¡“å°Žå…¥æŽ¨å¥¨
    - ç ”ç©¶æ–¹é‡å¤‰æ›´
    - ç‰¹è¨±å‡ºé¡˜

ai_agents:
  - name: AI Safety Researcher
    role: lead
    capabilities:
      - AIå®‰å…¨æ€§ç ”ç©¶
      - ãƒªã‚¹ã‚¯è©•ä¾¡
      - å€«ç†ãƒ¬ãƒ“ãƒ¥ãƒ¼
    focus_areas:
      - æ•µå¯¾çš„æ”»æ’ƒé˜²å¾¡
      - ãƒ¢ãƒ‡ãƒ«è§£é‡ˆå¯èƒ½æ€§
      - ãƒã‚¤ã‚¢ã‚¹è»½æ¸›
      
  - name: Adversarial ML Specialist
    role: specialist
    capabilities:
      - æ•µå¯¾çš„MLç ”ç©¶
      - æ”»æ’ƒæ‰‹æ³•åˆ†æž
      - é˜²å¾¡ç­–é–‹ç™º
    focus_areas:
      - ãƒ‡ãƒ¼ã‚¿ãƒã‚¤ã‚ºãƒ‹ãƒ³ã‚°
      - ãƒ¢ãƒ‡ãƒ«å›žé¿æ”»æ’ƒ
      - æ‘‚å‹•è€æ€§
      
  - name: Emerging Tech Scout
    role: specialist
    capabilities:
      - æŠ€è¡“æŽ¢ç´¢
      - ãƒˆãƒ¬ãƒ³ãƒ‰åˆ†æž
      - ãƒ—ãƒ­ãƒˆã‚¿ã‚¤ãƒ”ãƒ³ã‚°
    focus_areas:
      - æ–°æŠ€è¡“ç›£è¦–
      - ã‚¹ã‚¿ãƒ¼ãƒˆã‚¢ãƒƒãƒ—å‹•å‘
      - å­¦è¡“è«–æ–‡

collaboration_rules:
  with_architecture:
    - æ–°æŠ€è¡“å°Žå…¥æ¤œè¨Ž
    - PoCå®Ÿæ–½æ”¯æ´
    
  with_security:
    - æ–°è„…å¨å¯¾ç­–
    - è„†å¼±æ€§ç ”ç©¶
    
  with_data:
    - MLæŠ€è¡“å…±æœ‰
    - å®Ÿé¨“ãƒ‡ãƒ¼ã‚¿æä¾›

metrics:
  - name: research_papers_reviewed
    target: "> 20/month"
    alert: "< 10/month"
    
  - name: prototypes_developed
    target: "> 2/month"
    alert: "0"
    
  - name: tech_adoption_rate
    target: "> 30%"
    alert: "< 10%"
    
  - name: innovation_index
    target: "+10% YoY"
    alert: "-5% YoY"

improvement_areas:
  - è‡ªå‹•è«–æ–‡ç›£è¦–
  - å®Ÿé¨“è‡ªå‹•åŒ–
  - ãƒŠãƒ¬ãƒƒã‚¸ãƒ™ãƒ¼ã‚¹æ§‹ç¯‰
  - å¤–éƒ¨ç ”ç©¶å”åŠ›
